---
title: بناء روبوت يتبع الخط
hero_image: images/banner.png
description: اجعل عربة الروبوت تتبع المسار بنفسها
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3
version: 4.01
listed: true
ingredient: false
copyedit: true
last_tested: "2018-04-10"
curriculum: 3, design-0, programming-3, phys-comp-3, manufacture-2, community-0
interests: "robotics"
technologies: "electronic-components, raspberry-pi, python"
hardware: "electronic-components, raspberry-pi"
software: "python"
site_areas: projects
steps:
  - title: المقدمة
  - title: جهز الموصلات
  - title: وصل حساسات الخط
  - title: أختبر حساسات الخط
  - title: برمج خوارزمية تتبع الخط
  - title: خطط لخوارزمية أفضل
  - title: الخوارزمية النهائية
