---
title: Build a line-following robot
hero_image: images/banner.png
description: Make your robot buggy follow a track by itself
theme: red
duration: 3
version: 4
listed: true
ingredient: false
copyedit: true
last_tested: "2018-04-10"
curriculum: 3, design-0, programming-3, phys-comp-3, manufacture-2, community-0
interests: "robotics"
technologies: "electronic-components, raspberry-pi, python"
hardware: "electronic-components, raspberry-pi"
software: "python"
site_areas: projects
steps:
  - 
    title: Introduction
  - 
    title: Prepare the connectors
  - 
    title: Connect the line sensors
  - 
    title: Test the lines sensors
  - 
    title: Program a line following algorithm
  - 
    title: Plan a better algorithm
  - 
    title: The final algorithm
